session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  database: Tg_Bot_CHGK
bot:
  token: 1954880325:AAH-Ai3eahA1o6g_BZk3gdI5QeNjx3EgH5I

