version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    container_name: Tg_Bot_CHGK_DB
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env  
  web:
    image: igoryarets/tg_bot_chgk:latest
    container_name: AioHTTP_CHGK
    
    depends_on:
      - db
    env_file:
      - .env  
  nginx:
    image: nginx:1.19.3
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf      
    restart: always
    depends_on:
      - web

volumes:
  postgres_data:
