"""Added required tables

Revision ID: 170a4be8c17c
Revises: 
Create Date: 2023-03-19 12:08:06.167760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '170a4be8c17c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('players',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finish_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active_create_game', sa.Boolean(), nullable=False),
    sa.Column('is_active_start_game', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players_chats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['players.user_id'], )
    )
    op.create_table('players_games',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['players.user_id'], )
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captain_name', sa.Text(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('callback_id', sa.Integer(), nullable=True),
    sa.Column('start_round', sa.Integer(), nullable=False),
    sa.Column('finish_round', sa.Integer(), nullable=False),
    sa.Column('choice_questions', sa.Boolean(), nullable=False),
    sa.Column('timer_tour', sa.Boolean(), nullable=False),
    sa.Column('get_answer', sa.Boolean(), nullable=False),
    sa.Column('score_bot', sa.Integer(), nullable=False),
    sa.Column('score_team', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tours')
    op.drop_table('scores')
    op.drop_table('players_games')
    op.drop_table('players_chats')
    op.drop_table('games')
    op.drop_table('questions')
    op.drop_table('players')
    op.drop_table('chats')
    op.drop_table('admins')
    # ### end Alembic commands ###
