"""Added required tables

Revision ID: 9221a9981985
Revises: 07a0d7c4a566
Create Date: 2023-03-05 00:53:18.313247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9221a9981985'
down_revision = '07a0d7c4a566'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
